### ISSUE TITLE
报错UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 35: illegal multibyte sequence

### ISSUE THREAD

**Issue by sharcmz** [jammny/jws-cli#3]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 35: illegal multibyte sequence

![image](https://github.com/jammny/jws-cli/assets/81364075/e9f753a6-21c6-45d0-87c6-7e443c6d74e6)

**Comment by sharcmz** [comment]
windows  python 3.10.9

**Comment by jammny** [comment]
请在Linux环境使用，建议使用云服务器进行信息收集。
